Upgraded Dash to v2.1.0 to fix Dashboard issue #119
entropy-lab/entropy pull request #174
Opened 2022-02-20 09:44 UTC by urig

This PR fixes issue https://github.com/entropy-lab/entropy/issues/119. Dash is upgraded to v2.1.0 which includes a fix for the bug we were experiencing.

2022-02-20 11:48 UTC, galwiner approved these changes

2022-02-20 11:51 UTC, galwiner commented
@urig there's a conflict here (where you would expect, in the lock file) 
should we even have the lock file in version control?

2022-02-28 15:02 UTC, urig commented
> @urig there's a conflict here (where you would expect, in the lock file) should we even have the lock file in version control?

I'll fix the conflict now.

Having the lock file in source control is good for us because it speeds up the build process. It serves as a cached snapshot of our dependency tree.

2022-02-28 17:18 UTC, qguyk requested changes
@urig please change the line endings to the same it was before

2022-03-01 13:41 UTC, qguyk approved these changes

2022-03-01 13:41 UTC, merged